train:
  _target_: src.datasets.DigiCamDataset
  root: null
  split: train
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.DigiCamDataset
  root: null
  split: val
  instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.DigiCamDataset
  root: null
  split: test
  instance_transforms: ${transforms.instance_transforms.inference}
