defaults:
  - model: modular_leadmm5_prepost_drunet8m
  - _self_

dataset:
  _target_: src.datasets.custom_dir.CustomDirDataset
  root: data/custom
  limit: null
  shuffle_index: false

device: auto
batch_size: 1
num_workers: 0
output_dir: outputs/custom_inference
save_targets: true
checkpoint: checkpoints/leadmm5_prepost_drunet8m.pth
