log_step: 50
n_epochs: 100
epoch_len: 500
device_tensors: ["lensless", "mask", "lensed"]
resume_from: null
device: auto
override: false
monitor: "max val_PSNR"
save_period: 5
early_stop: ${trainer.n_epochs}
save_dir: saved
seed: 1
